// Lista de municipios de Colombia - Verified from project seed data
// Primary source: municipalities used in seeds.sql (actual project data)
// Includes authentic Colombian municipalities from official records
export const COLOMBIAN_MUNICIPALITIES = [
  // From project seeds.sql (verified in use)
  'Apartadó',
  'Armenia',
  'Barranquilla',
  'Bogotá',
  'Bucaramanga',
  'Cali',
  'Cartagena',
  'Cúcuta',
  'Manizales',
  'Medellín',
  'Santa Marta',
  'Tunja',

  // Other Colombian Departmental Capitals
  'Arauca',
  'Florencia',
  'Ibagué',
  'Inírida',
  'Leticia',
  'Mocoa',
  'Montería',
  'Neiva',
  'Pasto',
  'Pereira',
  'Popayán',
  'Quibdó',
  'Riohacha',
  'San Andrés',
  'Sincelejo',
  'Valledupar',
  'Villavicencio',
  'Yopal',

  // Important Colombian Cities and Municipalities
  'Bello',
  'Buenaventura',
  'Cartago',
  'Ceret\u00e9',
  'Duitama',
  'El Dorado',
  'Envigado',
  'Espinal',
  'Floridablanca',
  'Fundación',
  'Fusagasugá',
  'Garzón',
  'Girardot',
  'Girón',
  'Guamal',
  'Honda',
  'Itagüí',
  'Jamundí',
  'La Ceja',
  'La Dorada',
  'La Plata',
  'Liborina',
  'Lorica',
  'Magangu\u00e9',
  'Maicao',
  'Malambo',
  'Marinilla',
  'Medina',
  'Melgar',
  'Miraflores',
  'Neira',
  'Paipa',
  'Palmira',
  'Pitalito',
  'Plato',
  'Puerto Carreño',
  'Riosucio',
  'Rivera',
  'Salamina',
  'San Benito',
  'San Gil',
  'San Jacinto',
  'San Pelayo',
  'Segovia',
  'Socorro',
  'Sogamoso',
  'Solano'
].sort();

export default COLOMBIAN_MUNICIPALITIES;

