// Mapeo de ubicaciones de almacén para los 30 municipios de Córdoba, Colombia
export const WAREHOUSE_LOCATIONS = {
  'Ayapel': 'Almacén Ayapel',
  'Buenavista': 'Almacén Buenavista',
  'Canalete': 'Almacén Canalete',
  'Cereté': 'Almacén Cereté',
  'Chimá': 'Almacén Chimá',
  'Chinú': 'Almacén Chinú',
  'Ciénaga de Oro': 'Almacén Ciénaga de Oro',
  'Cotorra': 'Almacén Cotorra',
  'La Apartada': 'Almacén La Apartada',
  'Lorica': 'Almacén Lorica',
  'Los Córdobas': 'Almacén Los Córdobas',
  'Momil': 'Almacén Momil',
  'Montelíbano': 'Almacén Montelíbano',
  'Montería': 'Almacén Montería',
  'Moñitos': 'Almacén Moñitos',
  'Planeta Rica': 'Almacén Planeta Rica',
  'Pueblo Nuevo': 'Almacén Pueblo Nuevo',
  'Puerto Escondido': 'Almacén Puerto Escondido',
  'Puerto Libertador': 'Almacén Puerto Libertador',
  'Purísima de la Concepción': 'Almacén Purísima',
  'Sahagún': 'Almacén Sahagún',
  'San Andrés de Sotavento': 'Almacén San Andrés de Sotavento',
  'San Antero': 'Almacén San Antero',
  'San Bernardo del Viento': 'Almacén San Bernardo del Viento',
  'San Carlos': 'Almacén San Carlos',
  'San José de Uré': 'Almacén San José de Uré',
  'San Pelayo': 'Almacén San Pelayo',
  'Tierralta': 'Almacén Tierralta',
  'Tuchín': 'Almacén Tuchín',
  'Valencia': 'Almacén Valencia'
};

export default WAREHOUSE_LOCATIONS;
