// Mapeo de ubicaciones de almacén por municipio
export const WAREHOUSE_LOCATIONS = {
  'Apartadó': 'Almacén Central Apartadó',
  'Armenia': 'Centro Quindío',
  'Barranquilla': 'Bodega Principal Atlántico',
  'Bogotá': 'Bodega Distrital Cundinamarca',
  'Bucaramanga': 'Centro Santander',
  'Cali': 'Bodega Valle del Cauca',
  'Cartagena': 'Centro Bolívar',
  'Cúcuta': 'Almacén Norte de Santander',
  'Manizales': 'Centro Caldas',
  'Medellín': 'Centro Antioquia',
  'Santa Marta': 'Bodega Magdalena',
  'Tunja': 'Centro Boyacá',
  'Arauca': 'Bodega Arauca',
  'Florencia': 'Centro Caquetá',
  'Ibagué': 'Bodega Tolima',
  'Inírida': 'Centro Guainía',
  'Leticia': 'Centro Amazonas',
  'Mocoa': 'Bodega Putumayo',
  'Montería': 'Centro Córdoba',
  'Neiva': 'Bodega Huila',
  'Pasto': 'Centro Nariño',
  'Pereira': 'Centro Risaralda',
  'Popayán': 'Bodega Cauca',
  'Quibdó': 'Centro Chocó',
  'Riohacha': 'Bodega Guajira',
  'San Andrés': 'Centro Archipiélago',
  'Sincelejo': 'Centro Sucre',
  'Valledupar': 'Bodega Cesar',
  'Villavicencio': 'Centro Meta',
  'Yopal': 'Bodega Casanare',
  'Bello': 'Almacén Bello',
  'Buenaventura': 'Centro Buenaventura',
  'Cartago': 'Bodega Cartago',
  'Ceret\u00e9': 'Centro Córdoba',
  'Duitama': 'Bodega Duitama',
  'El Dorado': 'Centro Meta',
  'Envigado': 'Almacén Envigado',
  'Espinal': 'Bodega Tolima',
  'Floridablanca': 'Centro Floridablanca',
  'Fundación': 'Bodega Magdalena',
  'Fusagasugá': 'Centro Cundinamarca',
  'Garzón': 'Bodega Sur Huila',
  'Girardot': 'Centro Cundinamarca',
  'Girón': 'Almacén Girón',
  'Guamal': 'Centro Meta',
  'Honda': 'Bodega Honda',
  'Itagüí': 'Almacén Itagüí',
  'Jamundí': 'Bodega Jamundí',
  'La Ceja': 'Centro La Ceja',
  'La Dorada': 'Bodega La Dorada',
  'La Plata': 'Centro La Plata',
  'Liborina': 'Bodega Liborina',
  'Lorica': 'Centro Córdoba',
  'Magangu\u00e9': 'Bodega Bolívar',
  'Maicao': 'Centro Maicao',
  'Malambo': 'Centro Atlántico',
  'Marinilla': 'Almacén Marinilla',
  'Medina': 'Bodega Medina',
  'Melgar': 'Centro Tolima',
  'Miraflores': 'Bodega Miraflores',
  'Neira': 'Centro Caldas',
  'Paipa': 'Bodega Paipa',
  'Palmira': 'Centro Palmira',
  'Pitalito': 'Bodega Pitalito',
  'Plato': 'Centro Magdalena',
  'Puerto Carreño': 'Bodega Vichada',
  'Riosucio': 'Centro Risaralda',
  'Rivera': 'Bodega Rivera',
  'Salamina': 'Centro Caldas',
  'San Benito': 'Bodega San Benito',
  'San Gil': 'Centro San Gil',
  'San Jacinto': 'Bodega San Jacinto',
  'San Pelayo': 'Centro Córdoba',
  'Segovia': 'Bodega Segovia',
  'Socorro': 'Centro Socorro',
  'Sogamoso': 'Bodega Sogamoso',
  'Solano': 'Centro Caquetá'
};

export default WAREHOUSE_LOCATIONS;
